blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogUpdateView, BlogListView, BlogDetailView, BlogCreateView

app_name = BlogConfig.name


urlpatterns = [
    path('', BlogListView.as_view(), name='blog'),
    path('blog_create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_view/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from catalog.models import NULLABLE


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Cодержимое')
    image = models.ImageField(upload_to='blog/', verbose_name='Изображение', **NULLABLE)
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Признак публикации')
    count_view = models.IntegerField(default=0, verbose_name='Количество просмотров')
    notification_sent = models.BooleanField(default=False, verbose_name='Отправлено ли сообщение')

    def __str__(self):
        return f'{self.title}  {self.created_at}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DeleteView, UpdateView, DetailView, ListView
from pytils.translit import slugify
from django.core.mail import send_mail

from blog.models import Blog
from config import settings


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ('title', 'content')
    success_url = reverse_lazy('blog:blog')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_view += 1
        self.object.save()
        # проверка на условие отправки письма
        self.send_notification_email()
        return self.object

    def send_notification_email(self):
        from_email = settings.EMAIL_HOST_USER
        subject = 'Поздравляем'
        message = f'Ваша публикация {self.object.title} набрала {self.object.count_view} просмотров'
        recipient_email = settings.EMAIL_HOST_USER
        if self.object.count_view > 100 and not self.object.notification_sent:
            send_mail(subject, message, from_email, [recipient_email])
            print("Письмо успешно отправлено")

            self.object.notification_sent = True
            self.object.save()

class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('title', 'content')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:blog_view', args=[self.kwargs.get('pk')])

class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog')

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Информация
                    </h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <th>Заголовок</th>
                            <td>{{ blog.title }}</td>
                        </tr>
                        <tr>
                            <th>Количество просмотров</th>
                            <td>{{ blog.count_view }} </td>
                        </tr>
                        <tr>
                            <th>Cодержимое</th>
                            <td style="word-break: break-all">
                                {{ blog.content }}
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="card-footer">
                    <a href="{% url 'blog:blog' %}"
                       class="btn btn-sm btn-secondary">Вернуться</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form class="col-12" method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h2 class="card-title">
                        Добавление
                    </h2>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Создать</button>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-12" style="margin-bottom: 30px;">
    <a class="btn btn-success" href="{% url 'blog:blog_create' %}">
        Добавить новую запись
    </a>
</div>
{% for blog in blog_list %}
<div class="col-4">
    <div class="card">
        <h1 class="card-header text-center">
            {{blog.title}}
        </h1>
        <div class="card-body text-center">
            {% if blog.image %}
            <img src="{{ blog.image.url }}" class="img-fluid" alt="Изображение блога">
            {% else %}
            <p>Нет изображения</p>
            {% endif %}
        </div>
        <div class="card-footer text-center">
            <div class="btn-group">
                <a href="{% url 'blog:blog_view' blog.pk %}" class="btn btn-sm btn-secondary mr-1">Информация</a>
                <a href="#" class="btn btn-sm btn-success mr-1">Редактировать</a>
                <a href="#" class="btn btn-sm btn-danger">Удалить</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}