blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogUpdateView, BlogListView, BlogDetailView, BlogCreateView

app_name = BlogConfig.name


urlpatterns = [
    path('', BlogListView.as_view(), name='blog'),
    path('blog_create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_view/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ProductCreateView, ContactView, ProductUpdateView, \
    ProductDeleteView, ProductUnpublishView, ProductPublishView

app_name = CatalogConfig.name


urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('view/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('create/', ProductCreateView.as_view(), name='product_create'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),

    path('product_unpublish/<int:pk>/', ProductUnpublishView.as_view(), name='product_unpublish'),
    path('product_publish/<int:pk>/', ProductPublishView.as_view(), name='product_publish'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(**NULLABLE, verbose_name='Описание')

    def __str__(self):
        return f'{self.name} {self.description} '

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    image = models.ImageField(upload_to='product/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(default=0, verbose_name='Цена за покупку')
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateField(auto_now=True, verbose_name='Дата последнего изменения')

    is_published = models.BooleanField(default=False, verbose_name='признак публикации')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='пользователь')

    def __str__(self):
        return f'{self.name} {self.category} {self.created_at}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        permissions = [
            ('can_is_published_product', 'Can is_published product'),
            ('can_change_product_description', 'Can change product description'),
            ('can_change_product_category', 'Can change product category'),
        ]


class Version(models.Model):
    name = models.CharField(max_length=100, verbose_name='название версии')
    number_version = models.IntegerField(default=1, verbose_name='номер версии')
    current_version_indicator = models.BooleanField(default=True, verbose_name='признак текущей версии')

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def clean_name(self):
        clean_data = self.cleaned_data['name']
        ban_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for item_ban in ban_list:
            if item_ban in clean_data:
                raise forms.ValidationError(f'{item_ban} запрещенное слово')

        return clean_data

    def clean_description(self):
        clean_data = self.cleaned_data['description']
        ban_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for item_ban in ban_list:
            if item_ban in clean_data:
                raise forms.ValidationError(f'{item_ban} запрещенное слово')

        return clean_data


class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = ('name', 'number_version', 'current_version_indicator')

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.forms import inlineformset_factory
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Version


class ProductUnpublishView(View):
    model = Product

    def post(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        product.is_published = False
        product.save()
        return redirect(reverse('catalog:home'))

class ProductPublishView(View):
    model = Product

    def post(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        product.is_published = True
        product.save()
        return redirect(reverse('catalog:home'))


class ProductListView(ListView):
    model = Product


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'
    form_class = ProductForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.object
        current_version = product.version_set.filter(current_version_indicator=True).first()
        if current_version:
            context['current_version'] = current_version
        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form.html'
    permission_required = ('catalog.can_change_product_description', 'catalog.can_change_product_category')

    def has_permission(self):
        """Проверка на суперпользователя или автора публикации """
        if self.request.user.is_superuser or self.request.user == self.request.user:
            return True
        return super().has_permission()

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormSet = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormSet(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormSet(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:product_detail', args=[self.kwargs.get('pk')])


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:home')

    def test_func(self):
        obj = self.get_object()
        return self.request.user == obj.user


class ContactView(View):
    template_name = 'catalog/contact.html'

    def get(self, request):
        context = {'title': 'Контакты'}
        return render(request, self.template_name, context)

    def post(self, request):
        name = request.POST.get('name')
        email = request.POST.get('emails')
        message = request.POST.get('message')
        print(f'name:{name}\nemails:{email}\nmessage:{message}')

        context = {'title': 'Контакты'}
        return render(request, self.template_name, context)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">Какая-то информация</h4>
                    <p class="text-muted">какое-то описание.</p>
                </div>
                {% include 'catalog/includes/inc_menu.html' %}
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Album</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">
                {% block content %}

                {% endblock %}
            </div>

        </div>
    </div>
</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p> &copy; {% now 'Y' %}</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/contact.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
               какая-то информация
            </p>
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <h2>Написать</h2>
            <form method="post" action="{% url 'catalog:contact' %}">
                {% csrf_token %}
                <input class="form-control mb-2" name="name" placeholder="Введите ваше имя" required>
                <input class="form-control mb-2" name="email" placeholder="Введите ваш email" required>
                <textarea class="form-control mb-2" name="message" placeholder="Введите сообщение" required></textarea>
                <button type="submit" class="btn btn-primary form-control">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить "{{ product.name }}" ?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'catalog:home' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Информация
                    </h3>
                    <h6>Текущий пользователь: {{ request.user }}</h6>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <th>Название</th>
                            <td>{{ product.name }}</td>
                        </tr>
                        <tr>
                            <th>Цена</th>
                            <td>{{ product.price }} руб.</td>
                        </tr>
                        <tr>
                            <th>Описание</th>
                            <td style="word-break: break-all">
                                {{ product.description|slice:":100"|safe }}
                                {% if product.description|length > 100 %}...{% endif %}
                            </td>
                        </tr>
                        <tr>
                            <th>пользователь</th>
                            <td>{{product.user }}</td>
                        </tr>
                    </table>
                </div>
                <div class="card-footer">
                    <a href="{% url 'catalog:home' %}"
                       class="btn btn-sm btn-secondary">Вернуться к списку продуктов</a>
                </div>
            </div>
        </div>
        <div class="col-6">
             <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Информация
                    </h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        {% if current_version %}
                        <tr>
                            <th>Название</th>
                            <td>{{current_version.name }}</td>
                        </tr>
                        <tr>
                            <th>номер версии</th>
                            <td>{{current_version.number_version}} </td>
                        </tr>
                        {% else %}
                            <p>Текущая версия продукта не найдена</p>
                        {% endif %}
                    </table>
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form method="post">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if product %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p }}
                            {% if not forloop.last %}
                                <hr>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    {% if user.is_authenticated %}
    <a class="btn btn-success" href="{% url 'catalog:product_create' %}" style="margin-bottom: 30px;">
        Добавить новый продукт</a>
    {% endif %}
</div>
{% for product in product_list %}
<div class="col-4">
    {% if perms.catalog.can_is_published_product or user.is_superuser %}
        {% if not product.is_published %}
            <form method="post" action="{% url 'catalog:product_publish' product.pk %}">
                {% csrf_token %}
                <button type="submit" onclick="return confirm('Вы уверены, что хотите опубликовать продукт?')">Опубликовать</button>
            </form>

        {% elif product.is_published %}
            <form method="post" action="{% url 'catalog:product_unpublish' product.pk %}">
                {% csrf_token %}
                <button type="submit" onclick="return confirm('Вы уверены, что хотите отменить публикацию?')">Отменить публикацию</button>
            </form>
        {% endif %}
    {% endif %}

    {% if product.is_published == False %}
        <div class="card">
            <h2>Не опубликовано</h2>
        </div>
    {% elif product.is_published == True %}
        <div class="card ">
            <h1 class="card-header text-center">
                {{product.name}}
            </h1>
            <div class="card-body text-center">
                {% if product.image %}
                <img src="{{ product.image.url }}" style="max-width: 50%; max-height: 100%;">
                {% else %}
                <p>Нет изображения</p>
                {% endif %}
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-center  align-items-center">
                    {% if user.is_authenticated %}
                        <div class="btn-group">
                            <a href="{% url 'catalog:product_detail' product.pk %}"
                               class="btn btn-sm btn-secondary mr-1">Информация</a>
                            {% if product.user == request.user or user.is_superuser %}
                                <a href="{% url 'catalog:product_update' product.pk %}" type="button"
                                   class="btn btn-sm btn-success mr-1">Редактировать</a>
                                <a href="{% url 'catalog:product_delete' product.pk %}" type="button"
                                   class="btn btn-sm btn-danger">Удалить</a>
                                {% elif perms.catalog.can_change_product_description or perms.catalog.can_change_product_category %}
                                <a href="{% url 'catalog:product_update' product.pk %}" type="button"
                                    class="btn btn-sm btn-success mr-1">Изменить описание/категорию</a>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endif %}
</div>


{% endfor %}
{% endblock %}